name: CD Web

on:
  push:
    branches: ["main"]

jobs:
  client-build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and build Next.js project
        run: |
          cd web
          npm install
          npm run build --if-present
      - name: Restart pm2
        run: pm2 restart titan-web

  admin-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - name: Install dependencies and build Angular project
        run: |
          cd admin
          npm install
          npm run build
          pm2 restart admin
