name: Web Build A container

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build ./web --file ./web/Dockerfile --tag titan-project:$(date +%s)
      
