name: Web Build A NextJS

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build Next.js project
        run: |
          cd web
          npm ci
          npm run build --if-present

      - run: pm2 restart 0
