name: Web Build A NextJS

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js and dependencies, and build Next.js project
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        working-directory: web
        env:
          CI: true
          
      - run: npm install
        working-directory: web
        
      - run: npm run build --if-present
        working-directory: web
